# Generated by Django 4.2.2 on 2023-06-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_message_room_delete_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='dat',
            new_name='date',
        ),
        migrations.AddField(
            model_name='room',
            name='patient',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
