# Generated by Django 4.2.2 on 2023-06-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='billing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
