# Generated by Django 4.2.2 on 2023-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_appointment_billing_status_appointment_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='unread_messages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
