# Generated by Django 4.2.2 on 2023-06-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_room_unread_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='unread_messages',
        ),
    ]
